GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "oder pizza"
}

###

DELETE  http://localhost:3001/todo/delete/64b2e0d0d595f81fc0832761

###

PUT  http://localhost:3001/todo/complete/64b2c75eb88d607aaeb54672

